#!/bin/bash
# Catppuccin Macchiato — https://github.com/FelixKratz/JankyBorders
options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xffc6a0f6
	inactive_color=0xff494d64
)
borders "${options[@]}"
